### ISSUE TITLE
Error running cargo +nightly build --release in WSL

### ISSUE THREAD

**Issue by Neerucoder** [mc2-project/delphi#12]
Hello I am having an issue running the following command on my Windows Subsystem for Linux :

cargo +nightly build --release

The error is as follows 

Compiling protocols v0.1.0 (/home/test3/delphi/rust/protocols)
error[E0432]: unresolved import `io_utils::IMuxSync`
 --> protocols/src/lib.rs:2:5
  |
2 | use io_utils::IMuxSync;
  |     ^^^^^^^^^^^^^^^^^^ no `IMuxSync` in the root

error[E0432]: unresolved import `io_utils::IMuxSync`
  --> protocols/src/beavers_mul.rs:10:5
   |
10 | use io_utils::IMuxSync;
   |     ^^^^^^^^^^^^^^^^^^ no `IMuxSync` in the root

error[E0432]: unresolved import `io_utils::IMuxSync`
  --> protocols/src/gc.rs:18:5
   |
18 | use io_utils::IMuxSync;
   |     ^^^^^^^^^^^^^^^^^^ no `IMuxSync` in the root

error[E0432]: unresolved import `io_utils::IMuxSync`
 --> protocols/src/linear_layer.rs:8:5
  |
8 | use io_utils::IMuxSync;
  |     ^^^^^^^^^^^^^^^^^^ no `IMuxSync` in the root

error[E0432]: unresolved import `io_utils::IMuxSync`
  --> protocols/src/neural_network.rs:19:5
   |
19 | use io_utils::IMuxSync;
   |     ^^^^^^^^^^^^^^^^^^ no `IMuxSync` in the root

error[E0432]: unresolved import `io_utils::IMuxSync`
 --> protocols/src/quad_approx.rs:9:5
  |
9 | use io_utils::IMuxSync;
  |     ^^^^^^^^^^^^^^^^^^ no `IMuxSync` in the root

error[E0432]: unresolved import `io_utils::IMuxSync`
 --> protocols/src/bytes.rs:1:5
  |
1 | use io_utils::IMuxSync;
  |     ^^^^^^^^^^^^^^^^^^ no `IMuxSync` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `protocols` due to 7 previous errors

The current system I am using is  Ubuntu 20.04 LTS in WSL on a Windows 10 Laptop with NVIDIA 940 Ti
I would be really grateful if you can help mitigate this error or give me the environment/system specifications in which this code can be replicated in.

Thank You

**Comment by Neerucoder** [comment]
On running cargo +nightly build --verbose -v I get the following cause 

Caused by:
  process didn't exit successfully: `CARGO=/home/test3/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo CARGO_CRATE_NAME=protocols CARGO_MANIFEST_DIR=/home/test3/delphi/rust/protocols CARGO_PKG_AUTHORS='Pratyush Mishra:Ryan Lehmkuhl:Akshayaram Srinivasan:Wenting Zheng:Raluca Ada Popa' CARGO_PKG_DESCRIPTION='Cryptographic protocols for linear, ReLU, and quadratic activations used in Delphi' CARGO_PKG_HOMEPAGE='' CARGO_PKG_LICENSE=MIT/Apache-2.0 CARGO_PKG_LICENSE_FILE='' CARGO_PKG_NAME=protocols CARGO_PKG_REPOSITORY='https://github.com/mc2/delphi' CARGO_PKG_VERSION=0.1.0 CARGO_PKG_VERSION_MAJOR=0 CARGO_PKG_VERSION_MINOR=1 CARGO_PKG_VERSION_PATCH=0 CARGO_PKG_VERSION_PRE='' CARGO_PRIMARY_PACKAGE=1 LD_LIBRARY_PATH='/home/test3/delphi/rust/target/release/deps:/home/test3/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib:/home/test3/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib' rustc --crate-name protocols --edition=2018 protocols/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto -C debuginfo=2 -C metadata=352047f37232f9c9 -C extra-filename=-352047f37232f9c9 --out-dir /home/test3/delphi/rust/target/release/deps -C incremental=/home/test3/delphi/rust/target/release/incremental -L dependency=/home/test3/delphi/rust/target/release/deps --extern algebra=/home/test3/delphi/rust/target/release/deps/libalgebra-5b1e1c45960dafc0.rmeta --extern bench_utils=/home/test3/delphi/rust/target/release/deps/libbench_utils-fcd24b320142e30c.rmeta --extern bincode=/home/test3/delphi/rust/target/release/deps/libbincode-48aed193da5e0feb.rmeta --extern crossbeam=/home/test3/delphi/rust/target/release/deps/libcrossbeam-94ad3565603a03f2.rmeta --extern crypto_primitives=/home/test3/delphi/rust/target/release/deps/libcrypto_primitives-684d86b9085195eb.rmeta --extern io_utils=/home/test3/delphi/rust/target/release/deps/libio_utils-236c936b79f2e251.rmeta --extern ndarray=/home/test3/delphi/rust/target/release/deps/libndarray-dc6451f080d68992.rmeta --extern neural_network=/home/test3/delphi/rust/target/release/deps/libneural_network-c5c7aedce3478d5f.rmeta --extern num_traits=/home/test3/delphi/rust/target/release/deps/libnum_traits-46e6f25ac67e835d.rmeta --extern ocelot=/home/test3/delphi/rust/target/release/deps/libocelot-22312539de35b0f6.rmeta --extern protocols_sys=/home/test3/delphi/rust/target/release/deps/libprotocols_sys-8a941ea8396e48ae.rmeta --extern rand=/home/test3/delphi/rust/target/release/deps/librand-f960c32e97431496.rmeta --extern rayon=/home/test3/delphi/rust/target/release/deps/librayon-cce8fc9335c9c2aa.rmeta --extern scuttlebutt=/home/test3/delphi/rust/target/release/deps/libscuttlebutt-af6a0887339ba5d4.rmeta --extern serde=/home/test3/delphi/rust/target/release/deps/libserde-2660f9c43f2f6604.rmeta -C target-feature=+aes,+ssse3,+avx2 -C target-cpu=native -C opt-level=3 -L native=/home/test3/delphi/rust/target/release/build/base_conversion-fa718fcb3b5ee1a6/out -L native=/home/test3/delphi/rust/target/release/build/clear_on_drop-0c37e0c9a57dc0c8/out -L native=/home/test3/delphi/rust/target/release/build/torch-sys-b301eb6e76a74b4e/out/libtorch/libtorch/lib -L native=/home/test3/delphi/rust/target/release/build/torch-sys-b301eb6e76a74b4e/out -L native=/home/test3/delphi/rust/target/release/build/bzip2-sys-02ba674b6bbfcf60/out/lib -L native=/home/test3/delphi/rust/target/release/build/ocelot-f472f30bea91d02b/out -L /home/test3/delphi/rust/target/release/build/protocols-sys-01366afcadc5116d/out -L /home/test3/delphi/rust/target/release/build/protocols-sys-01366afcadc5116d/out/lib` (exit status: 1)

On Running lscpu I get the following output 

Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  2
Core(s) per socket:  2
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               142
Model name:          Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
Stepping:            9
CPU MHz:             2901.000
CPU max MHz:         2901.0000
BogoMIPS:            5802.00
Virtualization:      VT-x
Hypervisor vendor:   Windows Subsystem for Linux
Virtualization type: container
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr s
                     se sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 s
                     sse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave osxsave
                      avx f16c rdrand lahf_lm abm 3dnowprefetch fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx
                      rdseed adx smap clflushopt intel_pt ibrs ibpb stibp ssbd

**Comment by Neerucoder** [comment]
I have also gotten the same error running this on ubuntu 20.04 in VirtualBox with the following specs

![image](https://user-images.githubusercontent.com/22277219/126116362-3138e86d-ecf1-4e92-9b01-7b7500507720.png)
![image](https://user-images.githubusercontent.com/22277219/126116469-abcdd756-de7c-4b6c-a615-c93c07d3d6b3.png)

**Comment by ryanleh** [comment]
Hi,
Thanks for bringing this up! This is due to some recent changes I made to the structure of the `io-utils` library. I'll fix this sometime later this week but, if you would like to play around with things before then, I believe all of these errors can be solved by changing the line `use imux_io::IMuxSync` to `use imux_io::imux::IMuxSync`.

**Comment by Neerucoder** [comment]
Thank you,
I will give this a try

**Comment by Neerucoder** [comment]
I was able to resolve the error but now I am getting the following issue with Counting

error[E0432]: unresolved import `io_utils::CountingIO`
 --> experiments/src/lib.rs:7:5
  |
7 | use io_utils::CountingIO;
  |     ^^^^^^^^^^----------
  |     |         |
  |     |         help: a similar name exists in the module: `counting`
  |     no `CountingIO` in the root

error[E0432]: unresolved import `io_utils::CountingIO`
 --> experiments/src/latency/client.rs:5:5
  |
5 | use io_utils::CountingIO;
  |     ^^^^^^^^^^----------
  |     |         |
  |     |         help: a similar name exists in the module: `counting`
  |     no `CountingIO` in the root

error[E0432]: unresolved import `io_utils::CountingIO`
 --> experiments/src/latency/server.rs:5:5
  |
5 | use io_utils::CountingIO;
  |     ^^^^^^^^^^----------
  |     |         |
  |     |         help: a similar name exists in the module: `counting`
  |     no `CountingIO` in the root

Edit 

I was able to resolve this by using io_utils::counting::CountingIO

**Comment by ryanleh** [comment]
Ah yes, same thing as the other issue - you can change that to `io_utils::counting::CountingIO` and things should work.

**Comment by Neerucoder** [comment]
Thank You,
It worked
