### ISSUE TITLE
Cannot build on ubuntu-20.04 - error: failed to select a version for the requirement `crypto-mac = "^0.5"`

### ISSUE THREAD

**Issue by yixusama** [mc2-project/delphi#15]
when i use cargo +nightly build --release to build this project, an error occured.

lab@lab:~/pro/delphi/rust$ cargo +nightly build --release
    Updating crates.io index
    Updating git repository `https://github.com/pratyush/fancy-garbling/`
    Updating git repository `https://github.com/ryanleh/io-utils`
    Updating git repository `https://github.com/GaloisInc/ocelot/`
    Updating git repository `https://github.com/GaloisInc/scuttlebutt/`
error: failed to select a version for the requirement `crypto-mac = "^0.5"`
candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.1, ...
location searched: crates.io index
required by package `blake2 v0.7.0`
    ... which is depended on by `algebra v0.1.0 (/home/yixusama/pro/delphi/rust/algebra)`
    ... which is depended on by `crypto-primitives v0.1.0 (/home/yixusama/pro/delphi/rust/crypto-primitives)`
    ... which is depended on by `experiments v0.1.0 (/home/yixusama/pro/delphi/rust/experiments)`

**Comment by ryanleh** [comment]
Hi, 
This is due to an outdated dependency. This has been fixed in the most recent PR.

**Comment by yixusama** [comment]
Thank You
