### ISSUE TITLE
Error running ResNet32 NAS planner while running minionn NAS planner is ok

### ISSUE THREAD

**Issue by jyp4rk** [mc2-project/delphi#23]
Hi, I'm try to run NAS planner for resnet32 in this repository. I can run NAS for minionn with the command in end-to-end example, but similar command to resnet32 seems not working.

python resnet/resnet32_cifar100.py -n 7_layer -d ./tmp1 -a 7 -r resnet/pretrained/relu/model

jypark@gpu06 ~/delphi/python master* jypark ❯ python resnet/resnet32_cifar100.py -n 7_layer -d ./tmp1 -a 7 -r resnet/pretrained/relu/model                                                                                           21:07:45
2022-01-16 21:07:50,701	INFO resource_spec.py:216 -- Starting Ray with 5.27 GiB memory available for workers and up to 2.64 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
2022-01-16 21:07:51,213	WARNING pbt.py:204 -- `reward_attr` is deprecated and will be removed in a future version of Tune. Setting `metric=performance` and `mode=max`.
2022-01-16 21:07:51,766	INFO ray_trial_executor.py:121 -- Trial Cifar100Model_eda2bf7c: Setting up new remote runner.
== Status ==
Memory usage on this node: 46.6/62.6 GiB
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 4/40 CPUs, 1/1 GPUs, 0.0/5.27 GiB heap, 0.0/1.81 GiB objects
Result logdir: /home/jypark/delphi/python/tmp1/7_layer
Number of trials: 10 (1 RUNNING, 9 PENDING)
+------------------------+----------+-------+----------+------+
| Trial name             | status   | loc   | approx   | lr   |
|------------------------+----------+-------+----------+------|
| Cifar100Model_eda2bf7c | RUNNING  |       |          |      |
| Cifar100Model_eda2bf7d | PENDING  |       |          |      |
| Cifar100Model_eda2bf7e | PENDING  |       |          |      |
| Cifar100Model_eda2bf7f | PENDING  |       |          |      |
| Cifar100Model_eda2bf80 | PENDING  |       |          |      |
| Cifar100Model_eda2bf81 | PENDING  |       |          |      |
| Cifar100Model_eda2bf82 | PENDING  |       |          |      |
| Cifar100Model_eda2bf83 | PENDING  |       |          |      |
| Cifar100Model_eda2bf84 | PENDING  |       |          |      |
| Cifar100Model_eda2bf85 | PENDING  |       |          |      |
+------------------------+----------+-------+----------+------+

(pid=35053) WARNING:tensorflow:From /home/jypark/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
(pid=35053) Instructions for updating:
(pid=35053) If using Keras pass *_constraint arguments to layers.
(pid=35053) Approx 0: relu
(pid=35053) Approx 1: relu
(pid=35053) Approx 2: relu
(pid=35053) Approx 3: poly
(pid=35053) Approx 4: relu
(pid=35053) Approx 5: poly
(pid=35053) Approx 6: poly
(pid=35053) Approx 7: relu
(pid=35053) Approx 8: relu
(pid=35053) Approx 9: relu
(pid=35053) Approx 10: relu
(pid=35053) Approx 11: relu
(pid=35053) Approx 12: relu
(pid=35053) Approx 13: relu
(pid=35053) Approx 14: relu
(pid=35053) Approx 15: relu
(pid=35053) Approx 16: relu
(pid=35053) Approx 17: poly
(pid=35053) Approx 18: relu
(pid=35053) Approx 19: relu
(pid=35053) Approx 20: relu
(pid=35053) Approx 21: poly
(pid=35053) Approx 22: poly
(pid=35053) Approx 23: relu
(pid=35053) Approx 24: relu
(pid=35053) Approx 25: relu
(pid=35053) Approx 26: relu
(pid=35053) Approx 27: poly
(pid=35053) Approx 28: relu
(pid=35053) Approx 29: relu
(pid=35053) Approx 30: relu
(pid=35053) WARNING:tensorflow:From resnet/resnet32_cifar100.py:137: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.
(pid=35053)
(pid=35053) WARNING:tensorflow:From resnet/resnet32_cifar100.py:139: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
(pid=35053)
(pid=35053) 2022-01-16 21:07:56.754399: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
(pid=35053) 2022-01-16 21:07:56.785706: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2400000000 Hz
(pid=35053) 2022-01-16 21:07:56.789079: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x64eca70 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
(pid=35053) 2022-01-16 21:07:56.789138: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
(pid=35053) 2022-01-16 21:07:56.794545: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
(pid=35053) 2022-01-16 21:07:57.768597: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x66326b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
(pid=35053) 2022-01-16 21:07:57.768678: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Quadro GV100, Compute Capability 7.0
(pid=35053) 2022-01-16 21:07:57.769320: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
(pid=35053) name: Quadro GV100 major: 7 minor: 0 memoryClockRate(GHz): 1.627
(pid=35053) pciBusID: 0000:73:00.0
(pid=35053) 2022-01-16 21:07:57.770095: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
(pid=35053) 2022-01-16 21:07:57.773448: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
(pid=35053) 2022-01-16 21:07:57.776206: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcufft.so.10.0
(pid=35053) 2022-01-16 21:07:57.777003: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcurand.so.10.0
(pid=35053) 2022-01-16 21:07:57.780758: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusolver.so.10.0
(pid=35053) 2022-01-16 21:07:57.783165: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcusparse.so.10.0
(pid=35053) 2022-01-16 21:07:57.788970: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
(pid=35053) 2022-01-16 21:07:57.789590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
(pid=35053) 2022-01-16 21:07:57.789649: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
(pid=35053) 2022-01-16 21:07:57.790501: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
(pid=35053) 2022-01-16 21:07:57.790521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
(pid=35053) 2022-01-16 21:07:57.790532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
(pid=35053) 2022-01-16 21:07:57.791218: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 30592 MB memory) -> physical GPU (device: 0, name: Quadro GV100, pci bus id: 0000:73:00.0, compute capability: 7.0)
(pid=35053) WARNING:tensorflow:From resnet/resnet32_cifar100.py:141: The name tf.keras.backend.set_session is deprecated. Please use tf.compat.v1.keras.backend.set_session instead.
(pid=35053)
(pid=35053) 2022-01-16 21:07:58.581141: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/jypark/delphi/python/resnet/pretrained/relu/model: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
(pid=35053) Current epoch =  230
(pid=35053) Total =  330
(pid=35053) Ratio =  1.0
(pid=35053) Epoch 231/240
(pid=35053) WARNING:tensorflow:From /home/jypark/venv/lib/python3.7/site-packages/tensorflow_core/python/ops/math_grad.py:1375: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
(pid=35053) Instructions for updating:
(pid=35053) Use tf.where in 2.0, which has the same broadcast rule as np.where
(pid=35053) 2022-01-16 21:08:09.509060: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10.0
(pid=35053) 2022-01-16 21:08:09.708074: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2022-01-16 21:08:11,029	ERROR trial_runner.py:482 -- Error processing event.
Traceback (most recent call last):
  File "/home/jypark/venv/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 426, in _process_trial
    result = self.trial_executor.fetch_result(trial)
  File "/home/jypark/venv/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 378, in fetch_result
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)
  File "/home/jypark/venv/lib/python3.7/site-packages/ray/worker.py", line 1457, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(InvalidArgumentError): ray::Cifar100Model.train() (pid=35053, ip=147.47.123.236)
  File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task
  File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_task.function_executor
  File "/home/jypark/venv/lib/python3.7/site-packages/ray/tune/trainable.py", line 176, in train
    result = self._train()
  File "resnet/resnet32_cifar100.py", line 218, in _train
    initial_epoch=self.epoch)
  File "/home/jypark/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1296, in fit_generator
    steps_name='steps_per_epoch')
  File "/home/jypark/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_generator.py", line 265, in model_iteration
    batch_outs = batch_function(*batch_data)
  File "/home/jypark/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 1017, in train_on_batch
    outputs = self.train_function(ins)  # pylint: disable=not-callable
  File "/home/jypark/venv/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py", line 3476, in __call__
    run_metadata=self.run_metadata)
  File "/home/jypark/venv/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1472, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InvalidArgumentError: var and accum do not have the same shape[64] [8]
	 [[{{node training/SGD/SGD/update_batch_normalization_33/gamma/ResourceApplyKerasMomentum}}]]
== Status ==
Memory usage on this node: 51.1/62.6 GiB
PopulationBasedTraining: 0 checkpoints, 0 perturbs
Resources requested: 0/40 CPUs, 0/1 GPUs, 0.0/5.27 GiB heap, 0.0/1.81 GiB objects
Result logdir: /home/jypark/delphi/python/tmp1/7_layer
Number of trials: 10 (1 ERROR, 9 PENDING)

**Comment by ryanleh** [comment]
Hi @jyp4rk, thanks for bringing this up. Just wanted to let you know that I've seen this but I probably won't have cycles to investigate for a few weeks. Hope that isn't too much of a problem.

**Comment by jyp4rk** [comment]
Hi @ryanleh, Thanks for your answering the question. As minionn example works well, maybe I can just substitute minonn for ResNet. 

Thank you😀

**Comment by ryanleh** [comment]
Sorry about that, I hope that works out! 

As a related sidenote, I was very excited to see your (I'm assuming it's yours) [recent work](https://arxiv.org/pdf/2201.06699.pdf)! Haven't had a chance to read it through carefully yet but the results are quite impressive 😁

**Comment by jyp4rk** [comment]
Oh god, it is such an honor 😭.  The paper got inspired from Delphi's using BT. I really appreciate it. The paper will be updated soon with some more experiments.

Hope your next work would also be a great success as Delphi and MUSE.
