### ISSUE TITLE
Implement language models

### ISSUE THREAD

**Issue by DachengLi1** [mc2-project/delphi#26]
Hi there, I am really interested in the Delphi paper and the great implementation of this repo!  From what I understand, this system is optimized for CNN models. Due to the increasing interests in language models in the ML community, I am wondering if it is possible to implement secure transformer inference in this repo with the same level of efficiency? Is this purely an implementation-level effort or there may be other technical issues? Thanks a lot for any thoughts!

**Comment by Pratyush** [comment]
That is probably a research question of it's own, especially since the effective language models have billions of parameters!
