### ISSUE TITLE
Cmake Error + const_err issue (what worked for me)

### ISSUE THREAD

**Issue by ketanjog** [mc2-project/delphi#36]
I faced a lot of errors wrt versioning, and compilation when I was working with Ubuntu 18.04. I managed to set up Delphi after migrating to Ubuntu 20.04. After migrating I faced 2 errors:
1. Cmake version incompatible
2.  Could not install crypto_primitives. const_err is now a hard error.

I got the two errors resolved by following this set of commands. If anyone is facing similar issues, I would recommend just copy pasting each line on a fresh Ubuntu 20.04 machine:

# Install these necessary packages. They avoid some auxiliary errors you might encounter.
```
apt install cmake
apt install curl
apt-get install pkg-config libssl-dev
apt install g++
apt install git
apt-get install libclang-dev
apt-get install libc++-7-dev
apt-get install libc++abi-7-dev
```

# Install Rust
```
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
source .bashrc
source "$HOME/.cargo/env"
```

# install nightly
```
rustup install nightly
```

# Clone repo
```
git clone https://github.com/mc2-project/delphi
cd delphi/rust
```
# Build Delphi
```
cargo +nightly build --release
```
# For "const-err is hard error Error" :
Open delphi/rust/crypto-primitives/src/lib.rs
Remove "const_err" from Line 7

# If Cmake is not versioned to the latest (>3.12.0)
Go to https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line
Use method B (for developers, method A fails)

**Comment by ryanleh** [comment]
Thanks for this! I added some of the things you mentioned to the README just now

**Comment by aliarastehfard** [comment]
> I faced a lot of errors wrt versioning, and compilation when I was working with Ubuntu 18.04. I managed to set up Delphi after migrating to Ubuntu 20.04. After migrating I faced 2 errors:
> 
> 1. Cmake version incompatible
> 2. Could not install crypto_primitives. const_err is now a hard error.
> 
> I got the two errors resolved by following this set of commands. If anyone is facing similar issues, I would recommend just copy pasting each line on a fresh Ubuntu 20.04 machine:
> 
> # Install these necessary packages. They avoid some auxiliary errors you might encounter.
> ```
> apt install cmake
> apt install curl
> apt-get install pkg-config libssl-dev
> apt install g++
> apt install git
> apt-get install libclang-dev
> apt-get install libc++-7-dev
> apt-get install libc++abi-7-dev
> ```
> 
> # Install Rust
> ```
> curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
> source .bashrc
> source "$HOME/.cargo/env"
> ```
> 
> # install nightly
> ```
> rustup install nightly
> ```
> 
> # Clone repo
> ```
> git clone https://github.com/mc2-project/delphi
> cd delphi/rust
> ```
> 
> # Build Delphi
> ```
> cargo +nightly build --release
> ```
> 
> # For "const-err is hard error Error" :
> Open delphi/rust/crypto-primitives/src/lib.rs Remove "const_err" from Line 7
> 
> # If Cmake is not versioned to the latest (>3.12.0)
> Go to https://askubuntu.com/questions/355565/how-do-i-install-the-latest-version-of-cmake-from-the-command-line Use method B (for developers, method A fails)

Thank you! Do you know why I get these errors while trying to install these two?
apt-get install libc++-7-dev
apt-get install libc++abi-7-dev
-
<img width="563" alt="Screen Shot 2022-11-06 at 12 06 05 AM" src="https://user-images.githubusercontent.com/49977238/200153682-c0675462-577a-405c-9e1f-d3a6a73954d5.png">

**Comment by ryanleh** [comment]
@Mehrkish you shouldn't need those packages to build Delphi

**Comment by aliarastehfard** [comment]
> @Mehrkish you shouldn't need those packages to build Delphi

Noted Thanks
