### ISSUE TITLE
Errors when running the end-to-end example

### ISSUE THREAD

**Issue by whcjimmy** [mc2-project/delphi#37]
Hi, 

I recently tried to run the end-to-end example, and I faced an error in the "Performing inference with the model" subsection.

I followed the instructions to generate a test image, and I ran the command  ```cargo +nightly run --release --bin minionn-inference /tmp/model.npy 7``` to perform the inference. However, the argument seemed wrong (as shown in the figure).

How can I fix this error? 

Thanks! 

<img width="984" alt="截圖 2022-10-26 21 26 29" src="https://user-images.githubusercontent.com/4002046/198041621-cbcf5a6d-3712-486b-9ec2-13dc80384dc2.png">

**Comment by ryanleh** [comment]
Hi, the correct command is:
```
cargo +nightly run --release --bin minionn-inference -- --weights /tmp/model.npy --layers 7
```
I updated the README just now -- thanks for bringing this up!
