### ISSUE TITLE
error while running cargo +nightly build --release

### ISSUE THREAD

**Issue by aliarastehfard** [mc2-project/delphi#38]
![Screenshot 2022-11-04 115159](https://user-images.githubusercontent.com/49977238/200019903-0a153d6d-0d26-4f04-b90e-0f16d9686dc1.png)

**Comment by ryanleh** [comment]
Hi! I just pushed a fix for this 👍🏼

**Comment by aliarastehfard** [comment]
Thank you! Btw, I'm the one whose post you replied on Reddit
