### ISSUE TITLE
4 Warnings

### ISSUE THREAD

**Issue by aliarastehfard** [mc2-project/delphi#39]
Hi! Can you help me with these warnings? I'm using Linux (Ubuntu) subsystem for Windows 11.
---
![Screenshot_20221105_044536](https://user-images.githubusercontent.com/49977238/200140706-f7e3d18e-840a-44fb-a7b3-93d0456a9d4d.png)

**Comment by ryanleh** [comment]
They're just warnings, you can ignore them!

**Comment by aliarastehfard** [comment]
Word tnx
