### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'reward_attr' 

### ISSUE THREAD

**Issue by aliarastehfard** [mc2-project/delphi#40]
![python](https://user-images.githubusercontent.com/49977238/201412669-719d14dd-240b-4c2d-9473-e82c78220415.png)

**Comment by Mehrkish** [comment]
I used $pip install ray[tune] == 0.8.4 and it worked; however, I think the reward_attr has been removed in the recent versions.

**Comment by Mehrkish** [comment]
By the way the `$pip install ray[tune] == 0.8.0` doesn't work! I think they no longer support this version idk.

**Comment by ryanleh** [comment]
What version of ray are you using? My initial guess is that this is due to version mismatch

**Comment by aliarastehfard** [comment]
Yes, you are right. I had to change the version to `0.8.4` to solve it. I think the `0.8.0` version is no longer supported or maybe it has something to do with the version of my pip idk

**Comment by ryanleh** [comment]
Thanks for the heads up! I updated the README to use 0.8.4
