### ISSUE TITLE
Clarification on a Piece of Code

### ISSUE THREAD

**Issue by aliarastehfard** [mc2-project/delphi#43]
```
pub fn construct_minionn<R: RngCore + CryptoRng>(
    vs: Option<&tch::nn::Path>,
    batch_size: usize,
    num_poly: usize,
    rng: &mut R,
) -> NeuralNetwork<TenBitAS, TenBitExpFP> {
    let relu_layers = match num_poly {
        0 => vec![1, 3, 6, 8, 11, 13, 15],
        1 => vec![1, 3, 6, 8, 11, 13],
        2 => vec![1, 3, 6, 8, 11],
        3 => vec![3, 11, 13, 15],
        5 => vec![6, 11],
        6 => vec![11],
        7 => vec![],
        _ => unreachable!(),
    };
```
Hi! Can you help me understand what these vectors and the numbers included in them are? It is in the file [`minionn.rs`](https://github.com/mc2-project/delphi/blob/master/rust/experiments/src/minionn.rs#:~:text=%2D%3E%20NeuralNetwork%3C,%7D%3B)

**Comment by ryanleh** [comment]
The vector `relu_layers` defines which activation layers of the MiniONN network will use ReLU -- all other layers will use a polynomial activation. The specific pattern here, i.e. which activation layers are being chosen for ReLU vs. polynomial for a given bound, was discovered by the NAS.

**Comment by aliarastehfard** [comment]
Thank you! What is this `6 => vec![11]` implying for instance?

**Comment by ryanleh** [comment]
There are a total of 7 activation layers in MiniONN which are at indices (1, 3, 6, 8, 11, 13, 15). The line in question is stating that if we want 6 activations to be polynomials, we should just set layer 11 to be ReLU and all the others to be polynomials.

**Comment by aliarastehfard** [comment]
Got it! Thank you very much!

**Comment by WilliamYangXu** [comment]
Hi I wish to ask why there is no matching for 4?

**Comment by ryanleh** [comment]
If I recall, this is simply because the NAS planner was unable to find an accurate configuration for 4 polynomial layers. This doesn't really mean anything: I'm sure if you spent more time searching / tweaked some hyper-parameters than you could fine one.
