### ISSUE TITLE
Data Types

### ISSUE THREAD

**Issue by aliarastehfard** [mc2-project/delphi#46]
Hi,

I have a question regarding the source code that I was hoping you could help me answer at your convenience.

What is the purpose of [fixed_point.rs](https://github.com/mc2-project/delphi/blob/master/rust/algebra/src/fixed_point.rs)? What are `FixedPointParameters` and ` FixedPoint` used for? As for the generic data types that you use for constructing the neural netwotk layers (say the ones used in [Conv2dParams](https://github.com/mc2-project/delphi/blob/master/rust/neural-network/src/layers/linear/convolution.rs#:~:text=%2C%20C%3E-,Conv2dParams,-%3CF%2C), can I replace all of them with your custom `FixedPoint` data type? .. Seems more than a question :$

Thanks in advance

**Comment by ryanleh** [comment]
Delphi uses fixed point numbers to approximate floating point operations over a field -- this is fairly standard for cryptographic systems which operate on floating point numbers (e.g. anything ML related). You can read more about the representation in [this article](https://en.wikipedia.org/wiki/Fixed-point_arithmetic).

Yes, you should be able to do that. It might take a bit of massaging to get things to compile though -- not clear off the top of my head.

**Comment by aliarastehfard** [comment]
Thank you!
