### ISSUE TITLE
Updating C++ Implementation in Conv2d.cpp

### ISSUE THREAD

**Issue by aliarastehfard** [mc2-project/delphi#47]
I have a quick question. If I make changes to your C++ implementation in [`conv2d.cpp`](https://github.com/mc2-project/delphi/blob/master/rust/protocols-sys/c%2B%2B/src/lib/conv2d.cpp) on GitHub, will running cargo build be enough to see the effects of my changes? I assume I would need to generate a new `bindings.rs`, which is automatically taken care of by running cargo build. Do I need to do anything else manually?

**Comment by ryanleh** [comment]
As long as you're keeping the FFI the same (i.e. just changing internals of functions), then should everything should be handled automatically 👍🏼
