### ISSUE TITLE
Benchmarking the inference

### ISSUE THREAD

**Issue by PereteanuGeorge** [mc2-project/delphi#9]
@ryanleh @Pratyush 

Hello, 

I was wondering if there is any command to measure the time taken on my machine to run an encrypted inference. I am using the pre-trained model. 

Thank you so much!

**Comment by ryanleh** [comment]
Hi!

If you're benchmarking I'm assuming that you want to run the client and server on different machines? If that is the case then I would take a look at the `mnist-{client/server}`, `minionn-{client/server}`, `resnet32-{client/server}` binaries. 

For example, if you wanted to benchmark inference for MiniONN, you would run the following command on the machine acting as the server:
```
cargo +nightly run --bin minionn-server --all-features --release -- --layers $POLY_LAYERS
```
And the following command on the machine acting as the client:
```
cargo +nightly run --bin minionn-client --all-features --release -- --ip $IP --layers $POLY_LAYERS
```
where you should replace `$POLY_LAYERS` with the number of activations you wish to be polynomial approximations, and `$IP` with the IP address of your server machine.

Let me know if this helps!

**Comment by jyp4rk** [comment]
Hi, benchmark does not proceed from sending and receiving keys. How can I solve the problem?
![image](https://user-images.githubusercontent.com/37970459/132283237-ecb9e19f-ac34-407c-b497-45eb8f42aa78.png)
